Any user can create a question
IFilonov/QnA pull request #3
Opened 2019-03-05 19:29 UTC by IFilonov

2019-03-11 05:41 UTC, IFilonov commented on app/views/questions/show.html.slim
> += @question.answers.count
не убрал отладку

2019-03-13 14:49 UTC, vkurennov requested changes

2019-03-13 14:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def new
new не нужен, т.к. форма ответа должна быть на странице вопроса

2019-03-13 14:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def show
show тоже не нужен: все ответы должны быть видны на странице вопроса

2019-03-13 14:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user == @answer.user
* 1. Лучше сравнивать по user_id, чтобы не грузить ассоциацию из базы, она ведь не нужна.
* 2. Т.к. такая проверка будет встречаться часто, то лучше ее вынести в метод `User#author_of?`

2019-03-13 14:49 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user == @question.user
Замени проверку на вызов метода `User#author_of?`

2019-03-13 14:49 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +-if answer.persisted?
если ответ не сохранен, его тело выводить тоже нет смысла

2019-03-13 14:49 UTC, vkurennov commented on app/views/questions/new.html.slim
> += @question.inspect
удали это

2019-03-13 14:49 UTC, vkurennov commented on app/views/questions/new.html.slim
> += @question
выводи заголовок, пользователю не интересен объект

2019-03-13 14:49 UTC, vkurennov commented on app/views/questions/new.html.slim
> += @question.body
Зачем выводить тело ответа, если это форма на его создание и тела еще нет?

2019-03-13 14:49 UTC, vkurennov commented on app/views/questions/show.html.slim
> += link_to "Delete", question_path(@question), method: :delete
Ссылку на удаление стоит показывать только автору

2019-03-13 14:49 UTC, vkurennov commented on app/views/questions/show.html.slim
> += link_to "Log out", destroy_user_session_path, method: :delete
Эту ссылку надо показывать на всех страницах, поэтому ее стоит вынести в лейаут

2019-03-13 14:49 UTC, vkurennov commented on config/routes.rb
> +    resources :answers, shallow: true, only: [:new, :create, :show, :destroy]
new и show не нужны

2019-03-13 14:49 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'POST #create' do
тут надо проверить, что ответ еще и связывается с залогиненным юзером

2019-03-13 14:49 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
Тебя не смутило, что ты написал целый экшн в контроллере, а тестов на него нет. Любой код, который ты пишешь в каком-либо классе (модель или контроллер или еще что-то) обязательно надо покрывать тестами.

2019-03-13 14:49 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
здесь изменилось поведение метода, надо это отразить в тестах. у тебя теперь есть условие, соответственно, надо тестировать все возможные варианты

2019-03-13 14:49 UTC, vkurennov commented on spec/factories/questions.rb
> +    title { generate :title }
если название атрибута и sequence совпадает, то можно писать просто `title`, без блока. посмотри на фабрику юзеров из скирнкаста

2019-03-13 14:49 UTC, vkurennov commented on spec/factories/answers.rb
> +  sequence :answer_body do |n|
у тебя есть sequence для тела вопроса, его вполне можно использовать и для ответа.

2019-03-13 14:49 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +  given(:answer) { create(:answer, question: question, user: user) }
зачем создавать вопрос в тесте на создание вопроса? Ты же его через форму должен создать. Просто всегда в таких случаях есть шанс ложно-положительного теста, т.е. у тебя проверка пройдет не потому, что форма отработала, а потому что ты в базе напрямую создал ответ.

2019-03-13 14:49 UTC, vkurennov commented on spec/features/answer/create_spec.rb
> +
в начале/конце блоков/методов/классов пустые строки не ставятся

2019-03-13 14:49 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    fill_in 'Title', with: question.title
Это не тест на создание, поэтому тестировать форму не нужно. Здесь как раз надо сразу создать вопрос в базе через фабрики (причем до теста, так что объяви его через `given!`)

2019-03-13 14:49 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    visit question_path(question)
Не надо повторять все шаги пользователя для теста. Фича-тесты и так долгие. Если нужны какие-то данные заранее - создаем из в базе напрямую, а сам тест пишется только на тестируемое действие, в данном случае - на удаление.

2019-03-13 14:49 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    expect(page).to have_content 'Answer successfully deleted.'
а теперь надо проверить, что вопроса больше нет на странице

2019-03-13 14:49 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    click_on 'Delete answer'
лучше просто не показывать ему ссылку на удаление, кстати, похожий тест нужен и для незалогиненного юзера

2019-03-13 14:49 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    visit new_question_path
предыдущий коммент о том, что не надо повторять все действия юзера для подготвоки данных относится и ко всем остальным тестам тоже.

2019-03-13 14:49 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    fill_in 'Title', with: question.title
создай вопрос заранее напрямую в базе (для этого достаточно объявить его через `given!`).

2019-03-13 14:49 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    expect(page).to have_content 'Your question successfully deleted'
надо проверить, что вопроса больше нет на странице

2019-03-13 14:49 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    click_on 'Delete'
лучше просто не показывать ссылку

2019-03-13 14:49 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +  scenario 'Authenticated user deletes not his question with errors' do
похожий сценарий нужен и для незалогиненного юзера

2019-03-15 07:48 UTC, vkurennov requested changes

2019-03-15 07:48 UTC, vkurennov commented on app/models/user.rb
> +    id == item.user.id
Так ты ничего не добился. Идея в том, чтобы не грузить лишнюю ассоциацию из базы, ведь поле user_id уже есть у объекта. А ты сначала делаешь запрос к базе (тем самым порождая проблему n+1 запроса), а потом уже у него берешь id. В итоге, проблема остается.

2019-03-15 07:48 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  - if current_user && current_user.author_of?(answer)
Примени [safe navigation](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/), чтобы изабвиться от двойного условия

2019-03-15 07:48 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if current_user && current_user.author_of?(@question)
Примени safe navigation

2019-03-15 07:48 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer).user).to eq answer.user
Только `to eq user`, т.к. answer (который создан через фабрики) тут совсем не при чем. надо сравнивать с тем юзером, которого мы логиним в before

2019-03-15 07:48 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer } }.to change(question.answers, :count).by(-1)
Здесь в change должен стоять Answer, т.к. важно проверить, что в принципе удален ответ, вне зависимости от его связи с вопросом.

2019-03-15 07:48 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Тут надо также проверить связь с залогиненным юзером

2019-03-15 07:48 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    expect(page).not_to have_content 'Delete answer'
тольео лучше через `have_link` проверять

2019-03-15 07:48 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +    expect(page).not_to have_content 'Delete answer'
используй `have_link`

2019-03-15 07:48 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    expect(page).not_to have_content 'Delete question'
используй `have_link`

2019-03-15 07:48 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +    expect(page).not_to have_content 'Delete question'
используй `have_link`

2019-03-15 07:48 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
А где тест на метод `author_of?` Запомни: прежде чем написать/изменить код какого либо класса, надо начать с тестов.

2019-03-15 15:32 UTC, vkurennov approved these changes

2019-03-15 15:32 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.author_of?(question)).to eq true
лучше так: `expect(user).to be_author_of(question)`

2019-03-15 16:17 UTC, merged