7 Through ajax
IFilonov/QnA pull request #4
Opened 2019-04-01 16:02 UTC by IFilonov

2019-04-18 11:43 UTC, vkurennov requested changes

2019-04-18 11:43 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.erase_bests
все операции по снатию и назначению лучшего ответа должны быть атомарными, т.е. а) выполняться за один вызов метода модели (внутри, метод может делать несколько действий, конечно), б) все изменения должны быть обернуты в транзакцию.
кроме того, у тебя контроллер знает слишком много о логие назначения лучшео ответа,  а так быть не должно, контроллер должен быть тонким и знать только какой метод вызвать у какой модели, что загрузить и что отрендерить. вся остальная логика должна быть в модели.

Иными словами, здесь должна быть проверка на автора (кстати, где она?) и вызов метода у ответа, а уже этот метод должен сделать все остальное (и не забудь про транзакцию)

2019-04-18 11:43 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.update(question_params)
где проврека на автора?

2019-04-18 11:43 UTC, vkurennov commented on app/models/answer.rb
> +    scope :best, -> { where best: true }
у where нужно ставить скобки

2019-04-18 11:43 UTC, vkurennov commented on app/models/answer.rb
> +    def erase_bests
вот это надо объеденить в один метод и обернуть в транзакцию

2019-04-18 11:43 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    - if current_user&.author_of?(answer)
автор **вопроса** может назначать лучший ответ, а не автор ответа

2019-04-18 11:43 UTC, vkurennov commented on app/views/answers/best.js.erb
> +$('.answers').append("<%= j render @answer.question.answers %>")
append добавляет элементы к существующим. т.е. если  у тебя уже есть 5 ответов и выбран лучший, то эти же 5 ответов снова добавятся и продублируются на странице

2019-04-18 11:43 UTC, vkurennov commented on app/views/answers/destroy.js.erb
> +  $("<%= answer_id %>").hide();
лучше remove использовать  -полностью удалить элемент со страницы, а не скрыть его

2019-04-18 11:43 UTC, vkurennov commented on app/views/questions/_form.html.slim
> +  = f.text_area :title, readonly: true, id: 'question-title'
а зачем тут readonly? как вводить что-то в это поле?

2019-04-18 11:43 UTC, vkurennov commented on app/views/questions/_form.html.slim
> +  = f.text_area :body, readonly: true, id: 'question-body'
и тут непонятен флаг readonly

2019-04-18 11:43 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'user an author' do
раз есть контекст для автора (кстати, автора чего?), то должен быть и контекст не для автора. не дописал тесты - забыл написать код в контроллере, потому что тесты не показали тебе, что логика не полная

2019-04-18 17:04 UTC, IFilonov commented on app/controllers/answers_controller.rb
> +    @answer.erase_bests
Хотел сделать на один апдейт меньше )

2019-04-18 17:22 UTC, IFilonov commented on app/views/answers/best.js.erb
> +$('.answers').append("<%= j render @answer.question.answers %>")
Разве .html(''); не трет текущую структуру. Дублирования точно нет

2019-04-18 17:24 UTC, IFilonov commented on app/views/questions/_form.html.slim
> +  = f.text_area :title, readonly: true, id: 'question-title'
Вводить получается если нажать кнопу Edit, по кнопке Edit readonly снимается. Ну, такая реализация. Answer тоже сначала были readonly пока "не воткнулся в стену" (expect не видел текст заполненный fill_in объекта созданного из фабрики), потом переделал как по скринкасту.

2019-04-19 12:14 UTC, vkurennov approved these changes

2019-04-19 12:14 UTC, vkurennov commented on app/views/answers/best.js.erb
> +$('.answers').append("<%= j render @answer.question.answers %>")
а, ну да, не увидел, что там html, но это можно в одну команду записать - `replaceHtml`

2019-04-19 12:14 UTC, vkurennov commented on app/views/questions/_form.html.slim
> +  = f.text_area :title, readonly: true, id: 'question-title'
ок

2019-04-20 05:34 UTC, merged